import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import Link from "next/link";
import localFont from 'next/font/local'
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Poppin' - Discover What's Poppin' Near You.",
  description: "Generated by create next app",
};

const arcoFont = localFont({
  src: './arco.woff2',
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${arcoFont.className}`}
      >
        <Navbar />

        <div className="flex-grow">
          {children}
        </div>

        <footer className="mt-8 container mb-4">
          <div className="h-[1px] w-full bg-secondary"></div>

          <div className="w-full flex justify-between text-secondary mt-2">
            <p className="font-medium">Made by <Link href='https://thomasprice.me' className="underline">Thomas Price</Link></p>

            <Link className="font-medium" href='https://github.com/ThomasJPrice/poppin'>GitHub</Link>
          </div>
        </footer>

        <Toaster />
      </body>
    </html>
  );
}
